### ISSUE TITLE
Can not run bin/magento setup:upgrade if varnish is not installed

### ISSUE THREAD

**Issue by lsv** [scandipwa/persisted-query#15]
**Describe the bug**
If varnish is not reachable, you can not run `bin/magento setup:upgrade`

```
bin/magento setup:upgrade
Error flushing Varnish server. Host: "local.domain". PURGE response code: 405 message: Not Allowed
Server: nginx/1.10.3
```

**Additional context**
https://github.com/scandipwa/persisted-query/blob/2.x/src/Model/PurgeCache.php#L27

Make a check to see if varnish is actually enabled

**Comment by alfredsgenkins** [comment]
I think, it is actually a good point to do. We really can use persistence layer without varnish, time to drop this requirement!

**Comment by alfredsgenkins** [comment]
I will take a look, will release a new version of this soon!
