### ISSUE TITLE
Varnish purge request must contains header 'X-Magento-Tags-Pattern: .*

### ISSUE THREAD

**Issue by pastanislas** [scandipwa/persisted-query#6]
**Describe the bug**
bin/magento setup:upgrade throw 
'Error flushing Varnish server. Host: "varnish". PURGE response code: 400 message: X-Magento-Tags-Pattern header required'

**To Reproduce**
1 / run php bin/magento scandipwa:theme:bootstrap Scandiweb/pwa
2/  run bin/magento setup:upgrade 

**Expected behavior**
Setup being upgraded

**Additional context**

**Comment by eli-l** [comment]
Please provide Varnish logs for this message.

**Comment by pastanislas** [comment]
My bad, old VCL sorry about that. Thanks for your work

**Comment by eli-l** [comment]
Thanks for sharing this ;)

**Comment by ilyasdanish** [comment]
Hello elo-I,
I'm installing ScandiPWA in my existing magento setup. I had installed the it and run the bootstrap successfully but when i run the setup:upgrade i and getting error
" Error flushing Varnish server. Host: "staging.brandrange.ae". PURGE response code: 400 message: X-Magento-Tags-Pattern header required  
  Server: nginx    "

my server has varnish on port 8081
my server runing Redis

bin/magento
result: http://tinyurl.com/qv6cce9

bin/magento module:status
result: http://tinyurl.com/r26esje

bin/magento setup:upgrade
result: http://tinyurl.com/s52cehx

You can check my server running processes
http://tinyurl.com/uqakgua

Please help me out

Thanks Ilyas
