### ISSUE TITLE
Persistent query is required always

### ISSUE THREAD

**Issue by php4umagento** [scandipwa/persisted-query#9]
**Describe the bug**
When env.php is not present, e.g. during build phase inside pipelines or in Magento Cloud, lack of the settings for persistent query are causing fatal error

**To Reproduce**
1. Install vanilla magento
2. Install pwa 
3. Rename app/etc/env.php into something else or remove
4. Run any magento command - e.g. module:enable --all , or any other which does not require db connection

**Expected behavior**
Command executes without any errors

**Actual behavior**
Error                                                   
`Redis is not configured for persistent queries  `

**Comment by php4umagento** [comment]
Any update on that?

**Comment by alfredsgenkins** [comment]
Hey! @php4umagento 

Sorry, this went from my radar. Do you have any proposal to fix? I do not have an access to cloud at the moment, but I feel like reproducing this on normal setup should not be a problem.

But is not this expected? You have not configured persisted query - you will get this error. The question is - why is it running in the first place...

Also, the build phase - why M2 is even running on build phase?

Does not build just prepare an artifact? Maybe I am missing something. Our build do not interact with M2 in any way, deploys only.

I will not be able to look into this issue soon, we have redesign in progress. I am completely busy on that. I would be really happy if you could contribute on this one :)

Thanks, and sorry for late reply.

**Comment by php4umagento** [comment]
@alfredsgenkins - Magento Cloud prepares artifact but it is using bin/magento commands as well - those commands do not require magento to be operational at this stage.

Probably the easiest fix would be to not trigger that fatal error when Magento is not installed

something like you can find in ```public_html/vendor/magento/framework/App/Bootstrap.php```

```php
 /**
     * Determines whether application is installed
     *
     * @return bool
     */
    private function isInstalled()
    {
        /** @var \Magento\Framework\App\DeploymentConfig $deploymentConfig */
        $deploymentConfig = $this->objectManager->get(\Magento\Framework\App\DeploymentConfig::class);
        return $deploymentConfig->isAvailable();
    }
```

Source method

```Magento\Framework\App\DeploymentConfig```

```php
 /**
     * Checks if data available
     *
     * @return bool
     */
    public function isAvailable()
    {
        $this->data = null;
        $this->load();
        return isset($this->flatData[ConfigOptionsListConstants::CONFIG_PATH_INSTALL_DATE]);
    }
```

**Comment by php4umagento** [comment]
@alfredsgenkins - please check above PR

**Comment by eli-l** [comment]
@php4umagento 
Thanks for your commitment.
I took a look on this, solution seems legit, however you're calling the checks after you've already used the config, that will lead to fatal error.

**Comment by php4umagento** [comment]
@eli-l @alfredsgenkins 
I moved the fatal error to my method so it will not be triggered.

Also notice new check if Magento is installed

```
/**
     * Checks if persistent config is configured
     * But only when Magento is operational
     *
     * @throws \Exception
     */
    protected function checkPersistentQueriesConfig()
    {
        if (!$this->configExists() && $this->config->isAvailable()) {
            throw new \Exception('Redis is not configured for persistent queries');
        }
    }
```
